services:
  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=first
      - POSTGRES_PASSWORD=first
      - POSTGRES_DB=taro
    ports:
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "noemail@noemail.com"
      PGADMIN_DEFAULT_PASSWORD: "root"
    ports:
      - "5050:80"
    depends_on:
      - db